version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/bloom'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/client'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/json'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: '/packages/search'
    schedule:
      interval: 'daily'
      
  - package-ecosystem: 'npm'
    directory: '/packages/test-utils'
    schedule:
      interval: 'daily'
      
  - package-ecosystem: 'npm'
    directory: '/packages/time-series'
    schedule:
      interval: 'daily'
