# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "3.0"
    - nodejs_version: "4.0"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Typical npm stuff.
  - npm install

# Install Redis.
before_build:
  - nuget restore .\Hangfire.Redis.StackExchange.sln
  - packages\Redis-32.2.6.12.1\tools\redis-server.exe --service-install
  - packages\Redis-32.2.6.12.1\tools\redis-server.exe --service-start
  - '@ECHO Redis Started'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # We test multiple Windows shells
  - ps: "npm t # PowerShell" # Pass comment to PS for easier debugging
  - cmd: npm t

os:
  - Default Azure
  - Windows Server 2012 R2

# Don't actually build using MSBuild
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
