name: Benchmark

on:
  push:
    branches:
      - v4

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        redis-version: [6.x]

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.3.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup Redis
        uses: shogo82148/actions-setup-redis@v1.12.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Install Packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install Benchmark Packages
        run: npm ci
        working-directory: ./benchmark

      - name: Benchmark
        run: npm run start
        working-directory: ./benchmark
