name: Documentation

on:
  push:
    branches:
      - master
      - v4.0

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Use Node.js
        uses: actions/setup-node@v2.3.0
      - name: Install Packages
        run: npm ci
      - name: Build tests tools
        run: npm run build:tests-tools
      - name: Generate Documentation
        run: npm run documentation
      - name: Upload
        run: npm run gh-pages
