name: Documentation

on:
  push:
    branches:
      - v4

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - name: Use Node.js
        uses: actions/setup-node@v2.3.0

      - name: Install Packages
        run: npm ci

      - name: Generate Documentation
        run: npm run documentation

      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: documentation
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.BOT_PERSONAL_ACCESS_TOKEN }}
